### ISSUE TITLE
Document has bad maven dependency

### ISSUE THREAD

**Issue by eumji025** [DozerMapper/DozerMapper.github.io#8]
I find bad dependency in https://dozermapper.github.io/gitbook/documentation/gettingstarted.html 
tag is  `Downloading the Distribution`
the maven content is 
```xml
<dependency>
    <groupId>net.sf.dozer</groupId>
    <artifactId>dozer</artifactId>
    <version>6.1.0</version>
</dependency>
```

need change to

```xml
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>6.1.0</version>
</dependency>
```

**Comment by garethahealy** [comment]
The GH pages havent been rebuilt recently, but this issue has already been fixed:
- https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/documentation/gettingstarted.adoc

**Comment by eumji025** [comment]
Yes I know,maybe should commit again,I have encountered this situation before.
